"use client";

import { useActionState, useState } from "react";

import type { ErasureResultOut } from "@/lib/api/erasure";

import type { PrivacyActionState } from "./actions";

type Action = (
  prev: PrivacyActionState,
  formData: FormData,
) => Promise<PrivacyActionState>;
/** A preview and a cancel need neither the previous state nor the form. */
type BareAction = () => Promise<PrivacyActionState>;

function Result({ state }: { state: PrivacyActionState }) {
  if (state?.error)
    return (
      <p role="alert" className="error hint">
        {state.error}
      </p>
    );
  if (state?.ok && state.message)
    return (
      <div role="status" className="hint">
        <p>{state.message}</p>
        {state.result && <ResultView result={state.result} />}
      </div>
    );
  return null;
}

/** Counts per column and the rows to read by hand. Never a value: the API does not send one. */
export function ResultView({ result }: { result: ErasureResultOut }) {
  const entries = Object.entries(result.counts);
  return (
    <div>
      <p>
        <strong>{result.dry_run ? "Would change" : "Changed"}:</strong>{" "}
        {entries.length === 0
          ? "nothing."
          : entries.map(([column, n]) => `${column} (${n})`).join(", ")}
      </p>
      {result.review.length > 0 && (
        <details>
          <summary>
            {result.review.length}{" "}
            {result.review.length === 1 ? "row needs" : "rows need"} a manual
            review
            {result.review_truncated ? " (the list is cut off)" : ""}
          </summary>
          <p>
            These rows mention the name inside longer text. They were left
            unchanged. Open each one and decide.
          </p>
          <ul>
            {result.review.map((item) => (
              <li key={`${item.table}.${item.column}.${item.id}`}>
                {item.table}.{item.column}, row {item.id}
              </li>
            ))}
          </ul>
        </details>
      )}
      {!result.dry_run && result.exports_logged > 0 && (
        <p>
          {result.exports_logged}{" "}
          {result.exports_logged === 1 ? "export was" : "exports were"} made in
          this workspace. Files already downloaded are outside this system: find
          and delete them.
        </p>
      )}
      <p>{result.note}</p>
    </div>
  );
}

export function NewRequestForm({
  action,
  requestId,
  contacts,
  companies,
}: {
  action: Action;
  /** Generated by the page for each render: one id per submit attempt. */
  requestId: string;
  contacts: { id: string; name: string }[];
  companies: { id: string; name: string }[];
}) {
  const [state, formAction, pending] = useActionState(action, undefined);
  const [scope, setScope] = useState("contact");
  return (
    <form action={formAction}>
      <input type="hidden" name="request_id" value={requestId} />
      <fieldset>
        <legend>What should be erased?</legend>
        {[
          ["contact", "One contact"],
          [
            "company",
            "One company (for a sole proprietor, the business name is their name)",
          ],
          [
            "tenant",
            "The whole workspace (every contact, and all personal text)",
          ],
        ].map(([value, label]) => (
          <p key={value}>
            <label>
              <input
                type="radio"
                name="scope"
                value={value}
                checked={scope === value}
                onChange={() => setScope(value)}
                disabled={pending}
              />{" "}
              {label}
            </label>
          </p>
        ))}
      </fieldset>
      {scope === "contact" && (
        <p>
          <label htmlFor="erase-contact">Contact</label>{" "}
          <select
            id="erase-contact"
            name="contact_id"
            required
            disabled={pending}
          >
            {contacts.map((c) => (
              <option key={c.id} value={c.id}>
                {c.name}
              </option>
            ))}
          </select>
        </p>
      )}
      {scope === "company" && (
        <p>
          <label htmlFor="erase-company">Company</label>{" "}
          <select
            id="erase-company"
            name="company_id"
            required
            disabled={pending}
          >
            {companies.map((c) => (
              <option key={c.id} value={c.id}>
                {c.name}
              </option>
            ))}
          </select>
        </p>
      )}
      <button type="submit" disabled={pending}>
        {pending ? "Requesting..." : "Request erasure"}
      </button>
      <Result state={state} />
    </form>
  );
}

/** Owner only. Shows what a run would change, and changes nothing. */
export function PreviewForm({ action }: { action: BareAction }) {
  const [state, formAction, pending] = useActionState(action, undefined);
  return (
    <form action={formAction}>
      <button type="submit" className="secondary" disabled={pending}>
        {pending ? "Checking..." : "Preview"}
      </button>
      <Result state={state} />
    </form>
  );
}

/**
 * Owner only. Irreversible: the Owner types the words shown (ERASE plus the subject's name, or the workspace slug). The button stays
 * disabled until they match; the server checks the words again against what the API says, so this is only a convenience.
 */
export function ExecuteForm({ action, phrase }: { action: Action; phrase: string }) {
  const [state, formAction, pending] = useActionState(action, undefined);
  const [typed, setTyped] = useState("");
  const matches = typed.replace(/\s+/g, " ").trim() === phrase;
  return (
    <form action={formAction}>
      <label>
        To confirm, type <strong>{phrase}</strong>. This cannot be undone.
        <input
          type="text"
          name="confirm_text"
          value={typed}
          onChange={(event) => setTyped(event.target.value)}
          autoComplete="off"
          autoCapitalize="off"
          spellCheck={false}
          disabled={pending}
        />
      </label>{" "}
      <button type="submit" disabled={pending || !matches}>
        {pending ? "Erasing..." : "Erase now"}
      </button>
      <Result state={state} />
    </form>
  );
}

export function CancelForm({ action }: { action: BareAction }) {
  const [state, formAction, pending] = useActionState(action, undefined);
  return (
    <form action={formAction}>
      <button type="submit" className="secondary" disabled={pending}>
        {pending ? "Cancelling..." : "Cancel request"}
      </button>
      <Result state={state} />
    </form>
  );
}
