import type { CharacterSpec } from "./character";
import type { AgentId } from "./ids";

/**
 * Seven invented people: a spread of skin tones, hairstyles, builds and clothing, all drawn from one
 * warm palette (terracotta, charcoal, cream, olive, mustard, rose, slate blue). Nobody here is modelled
 * on a real person.
 */
export const PEOPLE: Record<AgentId, CharacterSpec> = {
  // the main agent: a little larger, charcoal blazer, an orange tie, grey in the hair
  main: {
    build: "m",
    skin: "#b07a58",
    hair: "#5a5655",
    hairStyle: "crop",
    beard: "beard",
    eye: "#4a3322",
    top: "#34323a",
    trim: "#26242b",
    bottom: "#26242b",
    outfit: "blazer",
    accent: "#ff773c",
    watch: true,
    sleeve: 1,
    size: 1.1,
  },
  lead_finder: {
    build: "f",
    skin: "#c98e66",
    hair: "#1d1716",
    hairStyle: "long",
    eye: "#3b2a1c",
    top: "#c2410c",
    trim: "#a2360a",
    bottom: "#3b3a44",
    outfit: "crew",
    sleeve: 0.6,
  },
  researcher: {
    build: "f",
    skin: "#f0c8a6",
    hair: "#6b4a2f",
    hairStyle: "bob",
    eye: "#4f7a8c",
    top: "#e4d2b6",
    trim: "#cdb694",
    bottom: "#4a4650",
    outfit: "cardigan",
    glasses: true,
    sleeve: 1,
  },
  requirement_analyst: {
    build: "m",
    skin: "#6a4330",
    hair: "#100c0b",
    hairStyle: "curly",
    eye: "#2a1a12",
    top: "#6b7a3a",
    trim: "#566330",
    bottom: "#33323a",
    outfit: "collar",
    sleeve: 0.55,
  },
  quote_writer: {
    build: "f",
    skin: "#e2b08a",
    hair: "#3a281d",
    hairStyle: "bun",
    eye: "#5a4a2a",
    top: "#d9a21b",
    trim: "#b8860f",
    bottom: "#403d48",
    outfit: "crew",
    sleeve: 0.62,
  },
  followup_desk: {
    build: "f",
    skin: "#8a5a3e",
    hair: "#0f0b0a",
    hairStyle: "puff",
    eye: "#2c1b12",
    top: "#c0627a",
    trim: "#a14a62",
    bottom: "#2f2e36",
    outfit: "crew",
    sleeve: 0.58,
  },
  order_desk: {
    build: "m",
    skin: "#d6a07a",
    hair: "#43342a",
    hairStyle: "crop",
    beard: "stubble",
    eye: "#44596a",
    top: "#4a5ab8",
    trim: "#3a4896",
    bottom: "#2f2e36",
    outfit: "collar",
    glasses: true,
    watch: true,
    sleeve: 0.6,
  },
};
