"""Generate packages/contracts/leads.schema.json and leads.ts from the leads models.

Same scheme as CRM/Evidence contracts (`make contracts`; test fails if stale).
"""

from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

from app.crm.contracts import _ts_type
from app.crm.models import Page
from app.leads import models as m

HEADER = (
    "// GENERATED by `make contracts` from services/ai-api/app/leads/models.py. Do not edit.\n"
    'import type { RecordOrigin } from "./crm";\n'
)
SHARED_WITH_CRM = {"RecordOrigin"}

RESPONSES: list[type[BaseModel]] = [
    m.IcpConfigOut,
    Page[m.IcpConfigOut],
    m.ImportBatchReport,
    m.LeadLabelOut,
    Page[m.LeadLabelOut],
    m.ReviewQueueLeadOut,
    Page[m.ReviewQueueLeadOut],
    m.ExportRecordOut,
]
REQUESTS: list[type[BaseModel]] = [
    m.IcpConfigCreate,
    m.ImportBatchRequest,
    m.LeadLabelCreate,
    m.ExportRequest,
]


def build_schema() -> dict[str, Any]:
    _, defs = models_json_schema(
        [(model, "serialization") for model in RESPONSES]
        + [(model, "validation") for model in REQUESTS],
        ref_template="#/$defs/{model}",
    )
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "leads.schema.json",
        "title": "Lead Review and ICP API contracts (T005)",
        "description": (
            "Generated from services/ai-api/app/leads/models.py by `make contracts`. "
            "Defines contracts for ICP configurations, lead import batches, candidate review "
            "queue, human lead labeling with scoring snapshots, and dataset exports."
        ),
        "$defs": dict(sorted(defs.get("$defs", {}).items())),
    }


def schema_text() -> str:
    return json.dumps(build_schema(), indent=2, sort_keys=False) + "\n"


def ts_text() -> str:
    defs = build_schema()["$defs"]
    lines = [HEADER]
    for name, node in defs.items():
        if name in SHARED_WITH_CRM:
            continue
        ts_name = name.replace("_", "")
        if "enum" in node:
            lines.append(f"export type {ts_name} = {_ts_type(node)};\n")
            continue
        props = node.get("properties", {})
        required = set(node.get("required", []))
        body = []
        for prop, spec in props.items():
            optional = "" if prop in required else "?"
            body.append(f"  {prop}{optional}: {_ts_type(spec)};")
        lines.append(f"export interface {ts_name} {{\n" + "\n".join(body) + "\n}\n")
    return "\n".join(lines)
