"""Generate packages/contracts/crm.schema.json and crm.ts from the API models.

The API models are the single definition; the committed files are generated from them
(`make contracts`) and a test fails if either file is stale. Responses in the integration tests are
validated against the generated JSON Schema, so the contract is checked against real traffic.
"""

from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

from app.crm import models as m

HEADER = "// GENERATED by `make contracts` from services/ai-api/app/crm/models.py. Do not edit.\n"

RESPONSES: list[type[BaseModel]] = [
    m.CompanyOut,
    m.ContactOut,
    m.ProductOut,
    m.LeadOut,
    m.OpportunityOut,
    m.ConsentResultOut,
    m.Page[m.CompanyOut],
    m.Page[m.ContactOut],
    m.Page[m.ProductOut],
    m.Page[m.LeadOut],
    m.Page[m.OpportunityOut],
]
REQUESTS: list[type[BaseModel]] = [
    m.CompanyCreate,
    m.CompanyUpdate,
    m.ContactCreate,
    m.ContactUpdate,
    m.ProductCreate,
    m.ProductUpdate,
    m.LeadCreate,
    m.LeadUpdate,
    m.OpportunityCreate,
    m.OpportunityUpdate,
    m.RecordConsentIn,
    m.SuppressIn,
    m.LiftSuppressionIn,
]


def build_schema() -> dict[str, Any]:
    _, defs = models_json_schema(
        [(model, "serialization") for model in RESPONSES]
        + [(model, "validation") for model in REQUESTS],
        ref_template="#/$defs/{model}",
    )
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "crm.schema.json",
        "title": "CRM API contracts (T003)",
        "description": (
            "Generated from services/ai-api/app/crm/models.py by `make contracts`. "
            "Request definitions forbid unknown properties: created_by, created_via, closed_at, "
            "tenant_id, archived_at and every consent / suppression column can never be sent."
        ),
        "$defs": dict(sorted(defs.get("$defs", {}).items())),
    }


def schema_text() -> str:
    return json.dumps(build_schema(), indent=2, sort_keys=False) + "\n"


# ----------------------------------------------------------------------------- TypeScript
def _ts_type(node: dict[str, Any]) -> str:
    if "$ref" in node:
        return str(node["$ref"]).rsplit("/", 1)[-1].replace("_", "")
    if "anyOf" in node:
        return " | ".join(
            sorted({_ts_type(option) for option in node["anyOf"]}, key=lambda t: (t == "null", t))
        )
    if "enum" in node:
        return " | ".join(json.dumps(v) for v in node["enum"])
    kind = node.get("type")
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        inner = _ts_type(node.get("items", {}))
        return f"({inner})[]" if "|" in inner else f"{inner}[]"
    if kind == "object":
        return "Record<string, unknown>"
    return "unknown"


def ts_text() -> str:
    defs = build_schema()["$defs"]
    lines = [HEADER]
    for name, node in defs.items():
        ts_name = name.replace("_", "")
        if "enum" in node:
            lines.append(f"export type {ts_name} = {_ts_type(node)};\n")
            continue
        props = node.get("properties", {})
        required = set(node.get("required", []))
        body = []
        for prop, spec in props.items():
            optional = "" if prop in required else "?"
            body.append(f"  {prop}{optional}: {_ts_type(spec)};")
        lines.append(f"export interface {ts_name} {{\n" + "\n".join(body) + "\n}\n")
    return "\n".join(lines)
