"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

import {
  cancelRun,
  setAgentsEnabled,
  startResearchRun,
  startSelftestRun,
} from "@/lib/api/agents";
import { ApiAuthError, ApiRequestError } from "@/lib/api/client";
import { isCanonicalUuid } from "@/lib/api/crm";
import { requireUser } from "@/lib/auth/session";

export type AgentActionState = { ok?: boolean; error?: string; message?: string } | undefined;

function field(formData: FormData, name: string): string {
  const value = formData.get(name);
  return typeof value === "string" ? value.trim() : "";
}

/** Short, generic messages only: a raw API body or a submitted value is never shown. */
function explain(error: unknown, whatFor: string): string {
  if (error instanceof ApiAuthError) redirect("/login");
  if (error instanceof ApiRequestError) {
    if (error.status === 403) return `Your role cannot ${whatFor}.`;
    if (error.status === 404) return "This workspace or record is not available.";
    if (error.status === 409 && error.code === "agents_disabled")
      return "Agents are not enabled for this workspace. An owner or admin can turn them on.";
    if (error.status === 409 && error.code === "token_expiring")
      return "Your session is about to expire. Sign in again and retry.";
    if (error.status === 409 && error.code === "lead_has_no_company")
      return "That lead has no company yet. Link a company to it first.";
    if (error.status === 409 && error.code === "company_has_no_website")
      return "That company has no website, so there is nothing to research.";
    if (error.status === 409 && error.code === "archived")
      return "That record is archived, so it cannot be a target.";
    if (error.status === 409)
      return "This form is out of date. Reload the page and try again.";
    if (error.status === 429 && error.code === "cost_cap_reached")
      return "This workspace's agents have used today's spending limit. Try again tomorrow (UTC).";
    if (error.status === 429) return "Too many agent runs right now. Try again later.";
    if (error.status === 503)
      return "Agents are not available right now (not configured, or busy). Try again later.";
  }
  return `Could not ${whatFor}. Try again.`;
}

/** The workspace switch (Owner/Admin; the API enforces it). Off by default. */
export async function toggleAgentsAction(
  tenantId: string,
  _prev: AgentActionState,
  formData: FormData,
): Promise<AgentActionState> {
  const user = await requireUser();
  if (!isCanonicalUuid(tenantId)) return { ok: false, error: "This workspace is not available." };
  const wanted = field(formData, "enabled");
  if (wanted !== "true" && wanted !== "false") return { ok: false, error: "Choose on or off." };
  try {
    await setAgentsEnabled(user.accessToken, tenantId, wanted === "true");
  } catch (error) {
    return { ok: false, error: explain(error, "change this setting") };
  }
  revalidatePath(`/app/tenants/${tenantId}/agents`);
  return { ok: true, message: wanted === "true" ? "Agents are on for this workspace." : "Agents are off for this workspace." };
}

/** Start one selftest run on a company. The run id is generated by the page, once per render (a retry re-sends it). */
export async function startRunAction(
  tenantId: string,
  _prev: AgentActionState,
  formData: FormData,
): Promise<AgentActionState> {
  const user = await requireUser();
  if (!isCanonicalUuid(tenantId)) return { ok: false, error: "This workspace is not available." };
  const runId = field(formData, "run_id");
  if (!isCanonicalUuid(runId)) return { ok: false, error: "This form is out of date. Reload the page and try again." };
  const companyId = field(formData, "company_id");
  if (!isCanonicalUuid(companyId)) return { ok: false, error: "Choose a company." };
  try {
    await startSelftestRun(user.accessToken, tenantId, { id: runId, companyId });
  } catch (error) {
    return { ok: false, error: explain(error, "start a run") };
  }
  revalidatePath(`/app/tenants/${tenantId}/agents`);
  return { ok: true, message: "Run started. Its suggestions will appear on the company page as 'agent suggestion, unreviewed'." };
}

/** Start one research run on a lead. The run id is generated by the page, once per render (a retry re-sends it). */
export async function startResearchRunAction(
  tenantId: string,
  _prev: AgentActionState,
  formData: FormData,
): Promise<AgentActionState> {
  const user = await requireUser();
  if (!isCanonicalUuid(tenantId)) return { ok: false, error: "This workspace is not available." };
  const runId = field(formData, "run_id");
  if (!isCanonicalUuid(runId)) return { ok: false, error: "This form is out of date. Reload the page and try again." };
  const leadId = field(formData, "lead_id");
  if (!isCanonicalUuid(leadId)) return { ok: false, error: "Choose a lead." };
  try {
    await startResearchRun(user.accessToken, tenantId, { id: runId, leadId });
  } catch (error) {
    return { ok: false, error: explain(error, "start a research run") };
  }
  revalidatePath(`/app/tenants/${tenantId}/agents`);
  return { ok: true, message: "Research started. Its suggestions will appear as 'agent suggestion, unreviewed', with the quote and the page they came from." };
}

export async function cancelRunAction(
  tenantId: string,
  runId: string,
): Promise<AgentActionState> {
  const user = await requireUser();
  if (!isCanonicalUuid(tenantId) || !isCanonicalUuid(runId))
    return { ok: false, error: "This run is not available." };
  try {
    await cancelRun(user.accessToken, tenantId, runId);
  } catch (error) {
    return { ok: false, error: explain(error, "cancel this run") };
  }
  revalidatePath(`/app/tenants/${tenantId}/agents`);
  return { ok: true, message: "Cancelled." };
}
