"use client";

import { useActionState } from "react";

import type { AgentActionState } from "./actions";
import { alertBox, btnMain, btnQuiet, hintInline, inlineForm, okBox, selectInline } from "@/components/v2/app/ui";

type Action = (prev: AgentActionState, formData: FormData) => Promise<AgentActionState>;

function Result({ state }: { state: AgentActionState }) {
  if (state?.error)
    return (
      <p role="alert" className={alertBox}>
        {state.error}
      </p>
    );
  if (state?.ok && state.message)
    return (
      <p role="status" className={okBox}>
        {state.message}
      </p>
    );
  return null;
}

/** The workspace switch. Rendered only for Owner/Admin (the API enforces the role regardless). */
export function AgentToggleForm({ action, enabled }: { action: Action; enabled: boolean }) {
  const [state, formAction, pending] = useActionState(action, undefined);
  return (
    <form action={formAction} className={inlineForm}>
      <input type="hidden" name="enabled" value={enabled ? "false" : "true"} />
      <button type="submit" className={btnMain} disabled={pending}>
        {pending ? "Saving..." : enabled ? "Turn agents off" : "Turn agents on"}
      </button>
      <Result state={state} />
    </form>
  );
}

export function StartRunForm({
  action,
  runId,
  companies,
}: {
  action: Action;
  /** Generated by the page for each render: one id per submit attempt. */
  runId: string;
  companies: { id: string; name: string }[];
}) {
  const [state, formAction, pending] = useActionState(action, undefined);
  return (
    <form action={formAction} className={inlineForm}>
      <input type="hidden" name="run_id" value={runId} />
      <label htmlFor="agent-company" className={hintInline}>
        Company
      </label>{" "}
      <select id="agent-company" name="company_id" required disabled={pending} className={selectInline}>
        {companies.map((c) => (
          <option key={c.id} value={c.id}>
            {c.name}
          </option>
        ))}
      </select>{" "}
      <button type="submit" className={btnMain} disabled={pending || companies.length === 0}>
        {pending ? "Starting..." : "Start selftest run"}
      </button>
      <Result state={state} />
    </form>
  );
}

/** One research run on one LEAD: the agent reads the lead's company's own website and proposes unreviewed suggestions. */
export function StartResearchForm({
  action,
  runId,
  leads,
}: {
  action: Action;
  /** Generated by the page for each render: one id per submit attempt. */
  runId: string;
  leads: { id: string; label: string }[];
}) {
  const [state, formAction, pending] = useActionState(action, undefined);
  return (
    <form action={formAction} className={inlineForm}>
      <input type="hidden" name="run_id" value={runId} />
      <label htmlFor="agent-lead" className={hintInline}>
        Lead
      </label>{" "}
      <select id="agent-lead" name="lead_id" required disabled={pending} className={selectInline}>
        {leads.map((l) => (
          <option key={l.id} value={l.id}>
            {l.label}
          </option>
        ))}
      </select>{" "}
      <button type="submit" className={btnMain} disabled={pending || leads.length === 0}>
        {pending ? "Starting..." : "Start research run"}
      </button>
      <Result state={state} />
    </form>
  );
}

export function CancelRunForm({ action }: { action: Action }) {
  const [state, formAction, pending] = useActionState(action, undefined);
  return (
    <form action={formAction} className={inlineForm}>
      <button type="submit" className={btnQuiet} disabled={pending}>
        {pending ? "Cancelling..." : "Cancel"}
      </button>
      <Result state={state} />
    </form>
  );
}
