"""Generate packages/contracts/evidence.schema.json and evidence.ts from the evidence models.

Same scheme as the CRM contracts (`make contracts`; a test fails if either file is stale). The JSON
Schema is self-contained (integration tests validate real responses against it). The TypeScript file
imports `RecordOrigin` from ./crm instead of redefining it, so the barrel export has no duplicates.
"""

from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

from app.crm.contracts import _ts_type
from app.crm.models import Page
from app.evidence import models as m

HEADER = (
    "// GENERATED by `make contracts` from services/ai-api/app/evidence/models.py. Do not edit.\n"
    'import type { RecordOrigin } from "./crm";\n'
)
SHARED_WITH_CRM = {"RecordOrigin"}

RESPONSES: list[type[BaseModel]] = [m.EvidenceOut, m.EvidenceLinkOut, Page[m.EvidenceLinkOut]]
REQUESTS: list[type[BaseModel]] = [m.EvidenceCreate]


def build_schema() -> dict[str, Any]:
    _, defs = models_json_schema(
        [(model, "serialization") for model in RESPONSES]
        + [(model, "validation") for model in REQUESTS],
        ref_template="#/$defs/{model}",
    )
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "evidence.schema.json",
        "title": "Evidence API contracts (T004)",
        "description": (
            "Generated from services/ai-api/app/evidence/models.py by `make contracts`. "
            "url, reference and snippet are UNTRUSTED text: show them as plain text, never as a "
            "link, and never follow or fetch them. The request forbids unknown properties: "
            "provider, created_by, created_via, tenant_id, archived_at and the link target can "
            "never be sent."
        ),
        "$defs": dict(sorted(defs.get("$defs", {}).items())),
    }


def schema_text() -> str:
    return json.dumps(build_schema(), indent=2, sort_keys=False) + "\n"


def ts_text() -> str:
    defs = build_schema()["$defs"]
    lines = [HEADER]
    for name, node in defs.items():
        if name in SHARED_WITH_CRM:
            continue
        ts_name = name.replace("_", "")
        if "enum" in node:
            lines.append(f"export type {ts_name} = {_ts_type(node)};\n")
            continue
        props = node.get("properties", {})
        required = set(node.get("required", []))
        body = []
        for prop, spec in props.items():
            optional = "" if prop in required else "?"
            body.append(f"  {prop}{optional}: {_ts_type(spec)};")
        lines.append(f"export interface {ts_name} {{\n" + "\n".join(body) + "\n}\n")
    return "\n".join(lines)
