"""Generate packages/contracts/agents.schema.json and agents.ts from the agent-run models.

Same scheme as the evidence contracts (`make contracts`; a test fails if either file is stale). The
JSON Schema is self-contained (integration tests validate real responses against it).
"""

from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

from app.agent_runs import models as m
from app.crm.contracts import _ts_type
from app.crm.models import Page

HEADER = (
    "// GENERATED by `make contracts` from services/ai-api/app/agent_runs/models.py. Do not edit.\n"
)

RESPONSES: list[type[BaseModel]] = [
    m.RunOut,
    m.CancelOut,
    m.AgentSettingsOut,
    m.ClaimSuggestionOut,
    m.ReviewOut,
    Page[m.RunOut],
]
REQUESTS: list[type[BaseModel]] = [m.RunStart, m.AgentSettingsIn, m.ReviewIn]


def build_schema() -> dict[str, Any]:
    _, defs = models_json_schema(
        [(model, "serialization") for model in RESPONSES]
        + [(model, "validation") for model in REQUESTS],
        ref_template="#/$defs/{model}",
    )
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "agents.schema.json",
        "title": "Agent run API contracts (T006)",
        "description": (
            "Generated from services/ai-api/app/agent_runs/models.py by `make contracts`. "
            "An agent claim is a SUGGESTION until a human accepts it: show it as "
            "'agent suggestion, unreviewed'. Claim values are UNTRUSTED text: show them as plain "
            "text. Requests forbid unknown properties: a tenant, an origin, a confidence of the "
            "agent's own or a provider can never be sent."
        ),
        "$defs": dict(sorted(defs.get("$defs", {}).items())),
    }


def schema_text() -> str:
    return json.dumps(build_schema(), indent=2, sort_keys=False) + "\n"


def ts_text() -> str:
    defs = build_schema()["$defs"]
    lines = [HEADER]
    for name, node in defs.items():
        ts_name = name.replace("_", "")
        if "enum" in node:
            lines.append(f"export type {ts_name} = {_ts_type(node)};\n")
            continue
        props = node.get("properties", {})
        required = set(node.get("required", []))
        body = []
        for prop, spec in props.items():
            optional = "" if prop in required else "?"
            body.append(f"  {prop}{optional}: {_ts_type(spec)};")
        lines.append(f"export interface {ts_name} {{\n" + "\n".join(body) + "\n}\n")
    return "\n".join(lines)
