// GENERATED by `make contracts` from services/ai-api/app/agent_runs/models.py. Do not edit.

export interface AgentSettingsIn {
  enabled: boolean;
}

export interface AgentSettingsOut {
  enabled: boolean;
}

export interface CancelOut {
  status: "running" | "succeeded" | "failed" | "cancelled" | "expired" | "killed";
  replayed: boolean;
}

export interface ClaimSuggestionOut {
  id: string;
  company_id: string | null;
  lead_id: string | null;
  predicate: string;
  value: string;
  confidence: "unverified" | "low" | "medium" | "high";
  claim_confidence: "unverified" | "low" | "medium" | "high";
  created_via: "manual" | "import" | "agent";
  agent_run_id: string | null;
  created_by: string | null;
  created_at: string;
  review_state: "not_applicable" | "unreviewed" | "accepted" | "rejected";
  review_confidence: "low" | "medium" | "high" | null;
  reviewed_by: string | null;
  reviewed_at: string | null;
}

export interface PageRunOut {
  items: RunOut[];
  next_cursor: string | null;
}

export interface ReviewIn {
  id: string;
  decision: "accepted" | "rejected";
  confidence?: "low" | "medium" | "high" | null;
  reason_code?: "incorrect" | "unsupported_by_evidence" | "outdated" | "duplicate" | "not_relevant" | null;
}

export interface ReviewOut {
  review_id: string;
  replayed: boolean;
  self_review: boolean;
}

export interface RunOut {
  id: string;
  agent_name: string;
  agent_version: string;
  status: "running" | "succeeded" | "failed" | "cancelled" | "expired" | "killed";
  started_by: string;
  company_id: string | null;
  lead_id: string | null;
  created_at: string;
  expires_at: string;
  finished_at: string | null;
  error_code: "budget" | "expired" | "killed" | "cancelled" | "disabled" | "tool_failed" | "model_failed" | "invalid_output" | null;
  cancel_requested: boolean;
  max_writes: number;
  writes_used: number;
  max_tool_calls: number;
  tool_calls_used: number;
  max_input_tokens: number;
  input_tokens_used: number;
  max_output_tokens: number;
  output_tokens_used: number;
  max_cost_micros: number;
  cost_micros_used: number;
}

export interface RunStart {
  id: string;
  agent: string;
  target_kind: "company" | "lead";
  target_id: string;
}
