// GENERATED by `make contracts` from services/ai-api/app/agent_runs/models.py. Do not edit.

export interface AddFieldIn {
  line?: number | null;
  field: "saree_type" | "fabric" | "colour" | "quantity" | "budget" | "deadline" | "delivery_city" | "payment_terms";
  value: string;
  quote?: string | null;
}

export interface AgentCostOut {
  day: string;
  cap_micros: number;
  settled_micros: number;
  open_micros: number;
  open: OpenReservationOut[];
}

export interface AgentSettingsIn {
  enabled: boolean;
}

export interface AgentSettingsOut {
  enabled: boolean;
}

export interface CancelOut {
  status: "running" | "succeeded" | "failed" | "cancelled" | "expired" | "killed";
  replayed: boolean;
}

export interface CaptureIn {
  id: string;
  channel: "email" | "whatsapp" | "form" | "other";
  received_at: string;
  subject?: string | null;
  text: string;
}

export interface CaptureOut {
  enquiry: EnquiryOut;
  text_changed: boolean;
  truncated: boolean;
}

export interface ClaimEvidenceOut {
  kind: string;
  stance: "supports" | "context" | "contradicts";
  provider: string;
  host: string | null;
  path: string | null;
  quote: string | null;
}

export interface ClaimSuggestionOut {
  id: string;
  company_id: string | null;
  lead_id: string | null;
  predicate: string;
  value: string;
  confidence: "unverified" | "low" | "medium" | "high";
  claim_confidence: "unverified" | "low" | "medium" | "high";
  created_via: "manual" | "import" | "agent";
  agent_run_id: string | null;
  created_by: string | null;
  created_at: string;
  review_state: "not_applicable" | "unreviewed" | "accepted" | "rejected";
  review_confidence: "low" | "medium" | "high" | null;
  reviewed_by: string | null;
  reviewed_at: string | null;
  counts_toward_score?: boolean;
  company_name?: string | null;
  evidence?: ClaimEvidenceOut[];
}

export interface DecisionIn {
  decision: "confirm" | "correct" | "reject";
  value?: string | null;
}

export interface EnquiryOut {
  id: string;
  lead_id: string;
  company_id: string | null;
  contact_id: string | null;
  channel: "email" | "whatsapp" | "form" | "other";
  received_at: string;
  subject: string | null;
  body: string;
  truncated_from: number | null;
  created_by: string | null;
  created_at: string;
  archived_at: string | null;
}

export interface FieldAddedOut {
  field_id: string;
  requirement_id: string;
  replayed: boolean;
}

export interface FieldDecisionOut {
  field_id: string;
  state: "proposed" | "confirmed" | "corrected" | "rejected";
  replayed: boolean;
}

export interface FieldValueOut {
  code: string | null;
  int_value: number | null;
  date_value: string | null;
  text: string | null;
  basis: string | null;
}

export interface FlagOut {
  kind: "missing" | "low_certainty" | "conflicting";
  field_key: "saree_type" | "fabric" | "colour" | "quantity" | "budget" | "deadline" | "delivery_city" | "payment_terms";
  line_no: number | null;
}

export interface OpenReservationOut {
  run_id: string;
  step_key: string;
  reserved_micros: number;
  run_status: "running" | "succeeded" | "failed" | "cancelled" | "expired" | "killed";
  created_at: string;
}

export interface PageRunOut {
  items: RunOut[];
  next_cursor: string | null;
}

export interface QuestionOut {
  code: string;
  text: string;
  field_key: "saree_type" | "fabric" | "colour" | "quantity" | "budget" | "deadline" | "delivery_city" | "payment_terms";
  line_no: number | null;
}

export interface RequirementActionOut {
  requirement_id: string;
  status: "draft" | "confirmed" | "superseded" | "discarded";
  replayed: boolean;
}

export interface RequirementFieldOut {
  id: string;
  line_no: number | null;
  field_key: "saree_type" | "fabric" | "colour" | "quantity" | "budget" | "deadline" | "delivery_city" | "payment_terms";
  value: FieldValueOut;
  display: string;
  certainty: "stated" | "implied" | "ambiguous";
  state: "proposed" | "confirmed" | "corrected" | "rejected";
  conflict: boolean;
  created_via: "manual" | "import" | "agent";
  quote: string | null;
  quote_start: number | null;
  quote_end: number | null;
  decided_by: string | null;
  decided_at: string | null;
}

export interface RequirementOut {
  id: string;
  status: "draft" | "confirmed" | "superseded" | "discarded";
  created_via: "manual" | "import" | "agent";
  agent_run_id: string | null;
  confirmed_by: string | null;
  confirmed_at: string | null;
  created_at: string;
}

export interface RequirementViewOut {
  requirement: RequirementOut | null;
  fields: RequirementFieldOut[];
  lines: number[];
  confirmable: boolean;
  ready_for_quote: boolean;
  flags: FlagOut[];
  questions: QuestionOut[];
}

export interface ReviewIn {
  id: string;
  decision: "accepted" | "rejected";
  confidence?: "low" | "medium" | "high" | null;
  reason_code?: "incorrect" | "unsupported_by_evidence" | "outdated" | "duplicate" | "not_relevant" | null;
}

export interface ReviewOut {
  review_id: string;
  replayed: boolean;
  self_review: boolean;
}

export interface RunOut {
  id: string;
  agent_name: string;
  agent_version: string;
  status: "running" | "succeeded" | "failed" | "cancelled" | "expired" | "killed";
  started_by: string;
  company_id: string | null;
  lead_id: string | null;
  enquiry_id?: string | null;
  created_at: string;
  expires_at: string;
  finished_at: string | null;
  error_code: "budget" | "expired" | "killed" | "cancelled" | "disabled" | "tool_failed" | "model_failed" | "invalid_output" | null;
  cancel_requested: boolean;
  max_writes: number;
  writes_used: number;
  max_tool_calls: number;
  tool_calls_used: number;
  max_input_tokens: number;
  input_tokens_used: number;
  max_output_tokens: number;
  output_tokens_used: number;
  max_cost_micros: number;
  cost_micros_used: number;
}

export interface RunStart {
  id: string;
  agent: "selftest" | "research" | "requirement";
  target_kind: "company" | "lead" | "enquiry";
  target_id: string;
}
