// GENERATED by `make contracts` from services/ai-api/app/crm/models.py. Do not edit.

export interface CompanyCreate {
  id: string;
  name: string;
  type?: CompanyType;
  website?: string | null;
  country?: string | null;
  region?: string | null;
  city?: string | null;
  industry?: string | null;
  tags?: string[];
}

export interface CompanyOut {
  id: string;
  created_by: string | null;
  created_via: RecordOrigin;
  created_at: string;
  updated_at: string;
  archived_at: string | null;
  name: string;
  type: CompanyType;
  website: string | null;
  country: string | null;
  region: string | null;
  city: string | null;
  industry: string | null;
  tags: string[];
}

export type CompanyType = "prospect" | "customer" | "supplier" | "other";

export interface CompanyUpdate {
  name?: string | null;
  type?: CompanyType | null;
  website?: string | null;
  country?: string | null;
  region?: string | null;
  city?: string | null;
  industry?: string | null;
  tags?: string[] | null;
}

export type ConsentBasis = "explicit_consent" | "contractual" | "legitimate_use" | "other";

export type ConsentChannel = "email" | "whatsapp" | "phone";

export interface ConsentResultOut {
  event_id: string | null;
  contact: ContactOut;
}

export type ConsentStatus = "unknown" | "granted" | "withdrawn";

export interface ContactCreate {
  id: string;
  company_id?: string | null;
  full_name: string;
  email?: string | null;
  phone?: string | null;
  job_title?: string | null;
}

export interface ContactOut {
  id: string;
  created_by: string | null;
  created_via: RecordOrigin;
  created_at: string;
  updated_at: string;
  archived_at: string | null;
  company_id: string | null;
  full_name: string;
  email: string | null;
  phone: string | null;
  job_title: string | null;
  email_consent: ConsentStatus;
  whatsapp_consent: ConsentStatus;
  phone_consent: ConsentStatus;
  suppressed_at: string | null;
  suppression_reason: SuppressionReason | null;
}

export interface ContactUpdate {
  company_id?: string | null;
  full_name?: string | null;
  email?: string | null;
  phone?: string | null;
  job_title?: string | null;
}

export type EvidenceType = "web_form" | "email_reply" | "verbal" | "written" | "imported" | "other";

export interface LeadCreate {
  id: string;
  company_id?: string | null;
  contact_id?: string | null;
  owner_user_id?: string | null;
  source?: string | null;
}

export interface LeadOut {
  id: string;
  created_by: string | null;
  created_via: RecordOrigin;
  created_at: string;
  updated_at: string;
  archived_at: string | null;
  company_id: string | null;
  contact_id: string | null;
  owner_user_id: string | null;
  status: LeadStatus;
  source: string | null;
  disqualified_reason: string | null;
}

export type LeadStatus = "new" | "in_review" | "qualified" | "disqualified";

export interface LeadUpdate {
  company_id?: string | null;
  contact_id?: string | null;
  owner_user_id?: string | null;
  status?: LeadStatus | null;
  source?: string | null;
  disqualified_reason?: string | null;
}

export interface LiftSuppressionIn {
  evidence_type: EvidenceType;
  evidence_ref: string;
}

export interface OpportunityCreate {
  id: string;
  company_id: string;
  contact_id?: string | null;
  lead_id?: string | null;
  owner_user_id?: string | null;
  title: string;
}

export interface OpportunityOut {
  id: string;
  created_by: string | null;
  created_via: RecordOrigin;
  created_at: string;
  updated_at: string;
  archived_at: string | null;
  company_id: string;
  contact_id: string | null;
  lead_id: string | null;
  owner_user_id: string | null;
  title: string;
  status: OpportunityStatus;
  lost_reason: string | null;
  closed_at: string | null;
}

export type OpportunityStatus = "open" | "won" | "lost";

export interface OpportunityUpdate {
  company_id?: string | null;
  contact_id?: string | null;
  lead_id?: string | null;
  owner_user_id?: string | null;
  title?: string | null;
  status?: OpportunityStatus | null;
  lost_reason?: string | null;
}

export interface PageCompanyOut {
  items: CompanyOut[];
  next_cursor: string | null;
}

export interface PageContactOut {
  items: ContactOut[];
  next_cursor: string | null;
}

export interface PageLeadOut {
  items: LeadOut[];
  next_cursor: string | null;
}

export interface PageOpportunityOut {
  items: OpportunityOut[];
  next_cursor: string | null;
}

export interface PageProductOut {
  items: ProductOut[];
  next_cursor: string | null;
}

export interface ProductCreate {
  id: string;
  sku: string;
  name: string;
  description?: string | null;
  unit?: string | null;
  category?: string | null;
  attributes?: Record<string, unknown>;
  active?: boolean;
}

export interface ProductOut {
  id: string;
  created_by: string | null;
  created_via: RecordOrigin;
  created_at: string;
  updated_at: string;
  archived_at: string | null;
  sku: string;
  name: string;
  description: string | null;
  unit: string | null;
  category: string | null;
  attributes: Record<string, unknown>;
  active: boolean;
}

export interface ProductUpdate {
  sku?: string | null;
  name?: string | null;
  description?: string | null;
  unit?: string | null;
  category?: string | null;
  attributes?: Record<string, unknown> | null;
  active?: boolean | null;
}

export interface RecordConsentIn {
  channel: ConsentChannel;
  status: ConsentStatus;
  basis?: ConsentBasis | null;
  evidence_type?: EvidenceType | null;
  evidence_ref?: string | null;
}

export type RecordOrigin = "manual" | "import" | "agent";

export interface SuppressIn {
  reason: SuppressionReason;
  evidence_type?: EvidenceType | null;
  evidence_ref?: string | null;
}

export type SuppressionReason = "opted_out" | "bounced" | "complained" | "legal" | "manual";
