// GENERATED by `make contracts` from services/ai-api/app/erasure/models.py. Do not edit.

export interface DataPolicyOut {
  real_data_allowed: boolean;
}

export interface ErasureRequestIn {
  id: string;
  scope: "contact" | "company" | "tenant";
  subject_id?: string | null;
}

export interface ErasureRequestOut {
  id: string;
  scope: "contact" | "company" | "tenant";
  subject_id: string | null;
  status: "pending" | "executing" | "executed" | "cancelled";
  requested_by: string;
  created_at: string;
  execute_after: string;
  executed_by: string | null;
  executed_at: string | null;
  cancelled_by: string | null;
  cancelled_at: string | null;
  result: ErasureResultOut | null;
}

export interface ErasureResultOut {
  request_id: string;
  scope: "contact" | "company" | "tenant";
  status: "executed" | "dry_run";
  dry_run: boolean;
  counts: Record<string, unknown>;
  review: ReviewItem[];
  review_truncated: boolean;
  exports_logged: number;
  note: string;
  replayed?: boolean;
}

export interface ExecuteIn {
  dry_run?: boolean;
}

export interface PageErasureRequestOut {
  items: ErasureRequestOut[];
  next_cursor: string | null;
}

export interface ReviewItem {
  table: string;
  column: string;
  id: string;
}
