// GENERATED by `make contracts` from services/ai-api/app/evidence/models.py. Do not edit.
import type { RecordOrigin } from "./crm";

export interface EvidenceCreate {
  id: string;
  kind: EvidenceKind;
  url?: string | null;
  reference?: string | null;
  snippet?: string | null;
  retrieved_at?: string | null;
  published_at?: string | null;
}

export type EvidenceKind = "web_page" | "document" | "email" | "listing" | "registry" | "note";

export interface EvidenceLinkOut {
  id: string;
  company_id: string | null;
  lead_id: string | null;
  claim_id: string | null;
  stance: EvidenceStance | null;
  created_by: string | null;
  created_via: RecordOrigin;
  created_at: string;
  archived_at: string | null;
  evidence: EvidenceOut;
}

export interface EvidenceOut {
  id: string;
  kind: EvidenceKind;
  provider: string;
  url: string | null;
  reference: string | null;
  snippet: string | null;
  retrieved_at: string;
  published_at: string | null;
  created_by: string | null;
  created_via: RecordOrigin;
  created_at: string;
  archived_at: string | null;
}

export type EvidenceStance = "supports" | "contradicts" | "context";

export interface PageEvidenceLinkOut {
  items: EvidenceLinkOut[];
  next_cursor: string | null;
}
