// GENERATED by `make contracts` from services/ai-api/app/leads/models.py. Do not edit.
import type { RecordOrigin } from "./crm";

export type ExportFormat = "csv" | "json";

export type ExportKind = "lead_labels";

export interface ExportRecordOut {
  id: string;
  tenant_id: string;
  kind: ExportKind;
  format: ExportFormat;
  row_count: number;
  content_sha256: string;
  created_by: string | null;
  created_via: RecordOrigin;
  created_at: string;
}

export interface ExportRequest {
  kind?: ExportKind;
  format?: ExportFormat;
}

export interface IcpConfigCreate {
  engine?: string;
  schema_version?: number;
  config: Record<string, unknown>;
}

export interface IcpConfigOut {
  id: string;
  tenant_id: string;
  version_no: number;
  engine: string;
  schema_version: number;
  config: Record<string, unknown>;
  config_sha256: string;
  created_by: string | null;
  created_via: RecordOrigin;
  created_at: string;
}

export interface ImportBatchCounts {
  rows: number;
  created: number;
  skipped_duplicate: number;
  ambiguous: number;
  rejected: number;
  companies_created: number;
  contacts_created: number;
  claims_created: number;
}

export interface ImportBatchReport {
  batch_id: string | null;
  replayed: boolean;
  dry_run: boolean;
  counts: ImportBatchCounts;
  rows: ImportRowOutcome[];
}

export interface ImportBatchRequest {
  batch_id: string;
  label?: string | null;
  rows: ImportRowInput[];
}

export type ImportOutcome = "created" | "skipped_duplicate" | "ambiguous" | "rejected";

export interface ImportRowInput {
  company_name: string;
  website?: string | null;
  country?: string | null;
  city?: string | null;
  industry?: string | null;
  categories?: string[];
  contact_name?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  contact_job_title?: string | null;
  source?: string | null;
  buyer_type?: string | null;
  size_band?: string | null;
  operating_status?: string | null;
  order_scale?: string | null;
}

export interface ImportRowOutcome {
  row: number;
  outcome: ImportOutcome;
  reason?: string | null;
  constraint?: string | null;
  sqlstate?: string | null;
  company_created: boolean;
  contact_created: boolean;
  attributes_written: number;
  attributes_kept: number;
  company_id?: string | null;
  contact_id?: string | null;
  lead_id?: string | null;
}

export type LeadLabel = "good" | "bad" | "maybe";

export interface LeadLabelCreate {
  id: string;
  label: LeadLabel;
  reason_code?: LeadLabelReason | null;
}

export interface LeadLabelOut {
  id: string;
  tenant_id: string;
  lead_id: string;
  label: LeadLabel;
  reason_code: LeadLabelReason | null;
  icp_version_id: string | null;
  score: number | null;
  score_max_reachable: number | null;
  snapshot: Record<string, unknown> | null;
  created_by: string | null;
  created_via: RecordOrigin;
  created_at: string;
}

export type LeadLabelReason = "not_our_market" | "wrong_product" | "too_small" | "too_large" | "inactive" | "not_a_business" | "no_contact_route" | "already_customer" | "duplicate" | "insufficient_info" | "payment_risk";

export interface PageIcpConfigOut {
  items: IcpConfigOut[];
  next_cursor: string | null;
}

export interface PageLeadLabelOut {
  items: LeadLabelOut[];
  next_cursor: string | null;
}

export interface PageReviewQueueLeadOut {
  items: ReviewQueueLeadOut[];
  next_cursor: string | null;
}

export interface ReviewQueueLeadOut {
  lead_id: string;
  status: string;
  source: string | null;
  created_at: string;
  company: Record<string, unknown>;
  contact: Record<string, unknown> | null;
  latest_label: LeadLabelOut | null;
  score?: number | null;
  score_max_reachable?: number | null;
  score_band?: string | null;
  snapshot?: Record<string, unknown> | null;
}
