"use client";

import { useActionState, useState } from "react";

import {
  LEAD_LABEL_REASON_LABELS,
  LEAD_LABEL_REASONS,
  type LeadLabel,
  type LeadLabelReason,
} from "@/lib/api/leads";

import { alertBox, btnBad, btnGood, btnMaybe, btnQuiet, formInline, hintInline, okBox, rowWrap, selectInline } from "@/components/v2/app/ui";

import { labelLeadAction, type LabelActionState } from "./actions";

interface LeadLabelFormProps {
  tenantId: string;
  leadId: string;
  /** Generated by the page for each render: one id per submit attempt (a retry re-sends it). */
  labelId: string;
  currentLabel?: LeadLabel | null;
  currentReason?: LeadLabelReason | null;
}

export function LeadLabelForm({
  tenantId,
  leadId,
  labelId,
  currentLabel,
  currentReason,
}: LeadLabelFormProps) {
  const [selectedLabel, setSelectedLabel] = useState<LeadLabel | "">("");
  const [reasonCode, setReasonCode] = useState<string>(currentReason || LEAD_LABEL_REASONS[0]);

  const boundAction = labelLeadAction.bind(null, tenantId, leadId);
  const [state, formAction, isPending] = useActionState<LabelActionState, FormData>(
    boundAction,
    {},
  );

  return (
    <form action={formAction} className={formInline}>
      <input type="hidden" name="label_id" value={labelId} />
      <input type="hidden" name="label" value={selectedLabel} />

      {selectedLabel === "bad" && (
        <div className={rowWrap}>
          <label htmlFor={`reason-${leadId}`} className={hintInline}>
            Reason:
          </label>
          <select
            id={`reason-${leadId}`}
            className={selectInline}
            name="reason_code"
            value={reasonCode}
            onChange={(e) => setReasonCode(e.target.value)}
            disabled={isPending}
            required
          >
            {LEAD_LABEL_REASONS.map((reason) => (
              <option key={reason} value={reason}>
                {LEAD_LABEL_REASON_LABELS[reason]}
              </option>
            ))}
          </select>
        </div>
      )}

      <div className={rowWrap}>
        <button
          type="submit"
          className={btnGood}
          disabled={isPending}
          onClick={() => setSelectedLabel("good")}
          aria-pressed={currentLabel === "good"}
        >
          {isPending && selectedLabel === "good" ? "Saving..." : "Good"}
        </button>

        <button
          type="submit"
          className={btnMaybe}
          disabled={isPending}
          onClick={() => setSelectedLabel("maybe")}
          aria-pressed={currentLabel === "maybe"}
        >
          {isPending && selectedLabel === "maybe" ? "Saving..." : "Maybe"}
        </button>

        {selectedLabel !== "bad" ? (
          <button
            type="button"
            className={btnBad}
            disabled={isPending}
            onClick={() => setSelectedLabel("bad")}
            aria-pressed={currentLabel === "bad"}
          >
            Bad...
          </button>
        ) : (
          <button
            type="submit"
            className={btnBad}
            disabled={isPending}
          >
            {isPending ? "Saving..." : "Confirm Bad"}
          </button>
        )}

        {selectedLabel === "bad" && (
          <button
            type="button"
            className={btnQuiet}
            disabled={isPending}
            onClick={() => setSelectedLabel("")}
          >
            Cancel
          </button>
        )}
      </div>

      {state?.error && (
        <p role="alert" className={alertBox}>
          {state.error}
        </p>
      )}
      {state?.ok && state?.message && (
        <p role="status" className={okBox}>
          {state.message}
        </p>
      )}
    </form>
  );
}
