import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";

const { labelLeadAction } = vi.hoisted(() => ({ labelLeadAction: vi.fn() }));
vi.mock("./actions", () => ({ labelLeadAction }));

import { LeadLabelForm } from "./lead-label-form";

const TENANT = "22222222-2222-2222-2222-222222222222";
const LEAD = "33333333-3333-3333-3333-333333333333";
const LABEL_ID = "55555555-5555-4555-8555-555555555555";

function sentIds(): string[] {
  return labelLeadAction.mock.calls.map(
    (call) => (call[3] as FormData).get("label_id") as string,
  );
}

describe("LeadLabelForm", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("carries the id generated by the page in a hidden field", () => {
    render(<LeadLabelForm tenantId={TENANT} leadId={LEAD} labelId={LABEL_ID} />);
    const hidden = document.querySelector(
      'input[name="label_id"]',
    ) as HTMLInputElement;
    expect(hidden.type).toBe("hidden");
    expect(hidden.value).toBe(LABEL_ID);
  });

  it("sends the SAME id on a retry of the same attempt (the server de-duplicates)", async () => {
    labelLeadAction.mockResolvedValue({ ok: false, error: "Could not save the label. Try again." });
    render(<LeadLabelForm tenantId={TENANT} leadId={LEAD} labelId={LABEL_ID} />);

    fireEvent.click(screen.getByRole("button", { name: "Good" }));
    await waitFor(() => expect(labelLeadAction).toHaveBeenCalledTimes(1));
    await screen.findByRole("alert");
    fireEvent.click(screen.getByRole("button", { name: "Good" }));
    await waitFor(() => expect(labelLeadAction).toHaveBeenCalledTimes(2));

    expect(sentIds()).toEqual([LABEL_ID, LABEL_ID]);
  });

  it("a double click is two submissions of the same attempt, never two different ids", async () => {
    labelLeadAction.mockResolvedValue({ ok: true, message: "Lead marked as maybe." });
    render(<LeadLabelForm tenantId={TENANT} leadId={LEAD} labelId={LABEL_ID} />);
    const maybe = screen.getByRole("button", { name: "Maybe" });
    fireEvent.click(maybe);
    fireEvent.click(maybe);
    await waitFor(() => expect(labelLeadAction).toHaveBeenCalled());
    expect(new Set(sentIds()).size).toBe(1);
    expect(sentIds()[0]).toBe(LABEL_ID);
  });
});
