"""Generate packages/contracts/erasure.schema.json and erasure.ts from the erasure models.

Same scheme as the agents contracts (`make contracts`; a test fails if either file is stale)."""

from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

from app.crm.contracts import _ts_type
from app.crm.models import Page
from app.erasure import models as m

HEADER = (
    "// GENERATED by `make contracts` from services/ai-api/app/erasure/models.py. Do not edit.\n"
)

RESPONSES: list[type[BaseModel]] = [
    m.ErasureRequestOut,
    m.ErasureResultOut,
    m.DataPolicyOut,
    Page[m.ErasureRequestOut],
]
REQUESTS: list[type[BaseModel]] = [m.ErasureRequestIn, m.ExecuteIn]


def build_schema() -> dict[str, Any]:
    _, defs = models_json_schema(
        [(model, "serialization") for model in RESPONSES]
        + [(model, "validation") for model in REQUESTS],
        ref_template="#/$defs/{model}",
    )
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "erasure.schema.json",
        "title": "Erasure API contracts (T006b)",
        "description": (
            "Generated from services/ai-api/app/erasure/models.py by `make contracts`. "
            "A result holds counts per column and row ids for manual review, never a value. "
            "Requests forbid unknown properties: a tenant, a status or a requester can never "
            "be sent."
        ),
        "$defs": dict(sorted(defs.get("$defs", {}).items())),
    }


def schema_text() -> str:
    return json.dumps(build_schema(), indent=2, sort_keys=False) + "\n"


def ts_text() -> str:
    defs = build_schema()["$defs"]
    lines = [HEADER]
    for name, node in defs.items():
        ts_name = name.replace("_", "")
        if "enum" in node:
            lines.append(f"export type {ts_name} = {_ts_type(node)};\n")
            continue
        props = node.get("properties", {})
        required = set(node.get("required", []))
        body = []
        for prop, spec in props.items():
            optional = "" if prop in required else "?"
            body.append(f"  {prop}{optional}: {_ts_type(spec)};")
        lines.append(f"export interface {ts_name} {{\n" + "\n".join(body) + "\n}\n")
    return "\n".join(lines)
