import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

import { AddEvidenceForm } from "./add-evidence-form";

const FORM_ID = "33333333-3333-3333-3333-333333333333";

describe("AddEvidenceForm", () => {
  it("has exactly the fields the milestone asks for", () => {
    render(<AddEvidenceForm action={vi.fn()} formId={FORM_ID} />);
    for (const label of [
      "Kind",
      "URL (optional)",
      "Reference (optional)",
      "Snippet (optional)",
      "Published on (optional)",
    ]) {
      expect(screen.getByLabelText(label)).toBeInTheDocument();
    }
    const form = screen.getByRole("form", { name: "Add evidence" });
    const names = [...form.querySelectorAll("input,select,textarea")]
      .map((el) => el.getAttribute("name"))
      .sort();
    expect(names).toEqual([
      "id",
      "kind",
      "published_at",
      "reference",
      "snippet",
      "url",
    ]);
    expect(
      screen.queryByLabelText(/provider|origin|tenant|archived/i),
    ).toBeNull();
  });

  it("offers every kind and states the typed-reference rule", () => {
    render(<AddEvidenceForm action={vi.fn()} formId={FORM_ID} />);
    const kinds = [...screen.getByLabelText("Kind").querySelectorAll("option")];
    expect(kinds.map((o) => o.getAttribute("value"))).toEqual([
      "web_page",
      "document",
      "email",
      "listing",
      "registry",
      "note",
    ]);
    expect(
      screen.getByLabelText("Reference (optional)"),
    ).toHaveAccessibleDescription(/lower-case prefix, a colon/);
    expect(
      screen.getByText(/Enter a URL, a reference, or both/),
    ).toBeInTheDocument();
  });

  it("limits the lengths in the browser (the server re-validates)", () => {
    render(<AddEvidenceForm action={vi.fn()} formId={FORM_ID} />);
    expect(screen.getByLabelText("URL (optional)")).toHaveAttribute(
      "maxlength",
      "2048",
    );
    expect(screen.getByLabelText("Snippet (optional)")).toHaveAttribute(
      "maxlength",
      "1000",
    );
    expect(screen.getByLabelText("Published on (optional)")).toHaveAttribute(
      "type",
      "date",
    );
  });

  it("carries the id generated by the page in a hidden field", () => {
    render(<AddEvidenceForm action={vi.fn()} formId={FORM_ID} />);
    const hidden = screen
      .getByRole("form", { name: "Add evidence" })
      .querySelector('input[name="id"]') as HTMLInputElement;
    expect(hidden.type).toBe("hidden");
    expect(hidden.value).toBe(FORM_ID);
  });

  it("keeps the same id across re-renders (a double submit repeats it)", () => {
    const { rerender } = render(
      <AddEvidenceForm action={vi.fn()} formId={FORM_ID} />,
    );
    rerender(<AddEvidenceForm action={vi.fn()} formId={FORM_ID} />);
    expect(
      (document.querySelector('input[name="id"]') as HTMLInputElement).value,
    ).toBe(FORM_ID);
  });

  it("shows nothing but the form until there is an error", () => {
    render(<AddEvidenceForm action={vi.fn()} formId={FORM_ID} />);
    expect(screen.queryByRole("alert")).toBeNull();
    expect(screen.getByRole("button", { name: "Add evidence" })).toBeEnabled();
  });
});
