import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

import { CreateCompanyForm } from "./create-company-form";

const FORM_ID = "33333333-3333-3333-3333-333333333333";

describe("CreateCompanyForm", () => {
  it("has the six fields the milestone asks for and nothing else", () => {
    render(<CreateCompanyForm action={vi.fn()} formId={FORM_ID} />);
    for (const label of [
      "Name",
      "Type",
      "Website",
      "Country",
      "City",
      "Industry",
    ]) {
      expect(screen.getByLabelText(label)).toBeInTheDocument();
    }
    const form = screen.getByRole("form", { name: "Create company" });
    const names = [...form.querySelectorAll("input,select")]
      .map((el) => el.getAttribute("name"))
      .sort();
    expect(names).toEqual([
      "city",
      "country",
      "id",
      "industry",
      "name",
      "type",
      "website",
    ]);
  });

  it("carries the id generated by the page in a hidden field", () => {
    render(<CreateCompanyForm action={vi.fn()} formId={FORM_ID} />);
    const hidden = screen
      .getByRole("form", { name: "Create company" })
      .querySelector('input[name="id"]') as HTMLInputElement;
    expect(hidden.type).toBe("hidden");
    expect(hidden.value).toBe(FORM_ID);
  });

  it("keeps the same id across re-renders (a double submit repeats it)", () => {
    const { rerender } = render(
      <CreateCompanyForm action={vi.fn()} formId={FORM_ID} />,
    );
    rerender(<CreateCompanyForm action={vi.fn()} formId={FORM_ID} />);
    const hidden = document.querySelector(
      'input[name="id"]',
    ) as HTMLInputElement;
    expect(hidden.value).toBe(FORM_ID);
  });

  it("offers the four company types, defaulting to prospect", () => {
    render(<CreateCompanyForm action={vi.fn()} formId={FORM_ID} />);
    const select = screen.getByLabelText("Type") as HTMLSelectElement;
    expect([...select.options].map((o) => o.value)).toEqual([
      "prospect",
      "customer",
      "supplier",
      "other",
    ]);
    expect(select.value).toBe("prospect");
  });

  it("submits to the bound server action and shows its error as an alert", async () => {
    const action = vi.fn(async () => ({
      error: "Check the values and try again.",
    }));
    render(<CreateCompanyForm action={action} formId={FORM_ID} />);
    fireEvent.change(screen.getByLabelText("Name"), {
      target: { value: "Acme" },
    });
    fireEvent.submit(screen.getByRole("form", { name: "Create company" }));
    expect(await screen.findByRole("alert")).toHaveTextContent(
      "Check the values and try again.",
    );
    expect(action).toHaveBeenCalledTimes(1);
  });
});
