import { CONFIDENCE_LABELS, type ClaimSuggestionOut } from "@/lib/api/agents";

import { LocalTime } from "../../local-time";
import { ReviewClaimForms } from "./review-claim-form";
import { reviewQueueClaimAction } from "./suggestion-actions";
import { SuggestionEvidence } from "./suggestion-evidence";
import { groupClaims } from "./suggestion-groups";
import { alertBox, bodyText, cardBox, cardGrid, mutedText, pageH2, sectionBlock, warnBorder, wrapAnywhere } from "@/components/v2/app/ui";

/**
 * The workspace's suggestion review screen: every agent suggestion that still needs a person, with what it rests on.
 *
 * AN AGENT CLAIM IS A SUGGESTION until a person accepts it; nothing here changes a score by itself. Claim values, quotes and
 * hosts are UNTRUSTED text and rendered as plain text only. Suggestions that disagree about the same thing (same company,
 * same predicate, different values) sit side by side so the reviewer compares them before accepting one. The cards wrap into
 * one column on a phone (`minmax(min(100%, 18rem), 1fr)`): no sideways scrolling.
 */
type Props = {
  tenantId: string;
  /** null = the API could not be reached / returned something unexpected. */
  claims: ClaimSuggestionOut[] | null;
  canReview: boolean;
  /** One pair of review ids per claim, generated by the page for this render. */
  reviewIds: Record<string, { accept: string; reject: string }>;
};

export function ReviewScreen({ tenantId, claims, canReview, reviewIds }: Props) {
  if (claims === null)
    return (
      <p role="alert" className={alertBox}>
        Could not load the suggestions from the API. Try again shortly.
      </p>
    );
  const groups = groupClaims(claims);
  if (groups.length === 0) return <p className={bodyText}>Nothing to review: there are no unreviewed suggestions.</p>;
  return (
    <div>
      <p className={mutedText}>
        {groups.length} thing{groups.length === 1 ? "" : "s"} to review.
      </p>
      {groups.map((group) => (
        <section key={group.key} aria-label={`${group.company}: ${group.predicate}`} className={sectionBlock}>
          <h2 className={`${pageH2} ${wrapAnywhere}`}>
            {group.company} · {group.predicate}
          </h2>
          {group.conflicting && (
            <p role="note" className={warnBorder}>
              <strong>These suggestions disagree.</strong> Compare them before you accept one.
            </p>
          )}
          <div className={cardGrid}>
            {group.claims.map((claim) => (
              <article key={claim.id} aria-label={`suggestion ${claim.value}`} className={cardBox}>
                <p>
                  <strong>{claim.value}</strong>
                </p>
                <p className={mutedText}>
                  {claim.review_state === "unreviewed"
                    ? "agent suggestion, unreviewed"
                    : `Approved by a person${claim.review_confidence ? ` · ${CONFIDENCE_LABELS[claim.review_confidence]}` : ""}`}
                  {" · "}
                  <LocalTime iso={claim.created_at} />
                </p>
                {!claim.counts_toward_score && (
                  <p className={mutedText}>This kind of note is not part of any score yet.</p>
                )}
                <SuggestionEvidence evidence={claim.evidence} />
                {canReview && claim.review_state === "unreviewed" && reviewIds[claim.id] && (
                  <ReviewClaimForms
                    claimId={claim.id}
                    acceptId={reviewIds[claim.id].accept}
                    rejectId={reviewIds[claim.id].reject}
                    accept={reviewQueueClaimAction.bind(null, tenantId, claim.id, claim.counts_toward_score === true)}
                    reject={reviewQueueClaimAction.bind(null, tenantId, claim.id, claim.counts_toward_score === true)}
                  />
                )}
              </article>
            ))}
          </div>
        </section>
      ))}
    </div>
  );
}
