import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";

import { ReviewClaimForms } from "./review-claim-form";

const CLAIM = "44444444-4444-4444-4444-444444444444";
const ACCEPT_ID = "55555555-5555-4555-8555-555555555555";
const REJECT_ID = "66666666-6666-4666-8666-666666666666";

const accept = vi.fn();
const reject = vi.fn();

function renderForms() {
  return render(
    <ReviewClaimForms
      claimId={CLAIM}
      acceptId={ACCEPT_ID}
      rejectId={REJECT_ID}
      accept={accept}
      reject={reject}
    />,
  );
}

describe("ReviewClaimForms", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    accept.mockResolvedValue({ ok: true, message: "Accepted." });
    reject.mockResolvedValue({ ok: true, message: "Rejected." });
  });

  it("gives accept and reject their OWN review ids, generated by the page", () => {
    renderForms();
    const ids = Array.from(document.querySelectorAll<HTMLInputElement>('input[name="review_id"]'));
    expect(ids.map((i) => i.value)).toEqual([ACCEPT_ID, REJECT_ID]);
    expect(ids.every((i) => i.type === "hidden")).toBe(true);
    expect(new Set(ids.map((i) => i.value)).size).toBe(2);
  });

  it("offers exactly low, medium and high to accept as, and the five reasons to reject with", () => {
    renderForms();
    const confidence = screen.getByLabelText(/accept as/i) as HTMLSelectElement;
    expect(Array.from(confidence.options).map((o) => o.value)).toEqual(["low", "medium", "high"]);
    const reason = screen.getByLabelText(/reject because/i) as HTMLSelectElement;
    expect(Array.from(reason.options).map((o) => o.value)).toEqual([
      "incorrect",
      "unsupported_by_evidence",
      "outdated",
      "duplicate",
      "not_relevant",
    ]);
  });

  it("accept submits the accept id, the decision and the chosen confidence", async () => {
    renderForms();
    fireEvent.change(screen.getByLabelText(/accept as/i), { target: { value: "high" } });
    fireEvent.click(screen.getByRole("button", { name: "Accept" }));
    await waitFor(() => expect(accept).toHaveBeenCalledTimes(1));
    const data = accept.mock.calls[0][1] as FormData;
    expect([data.get("review_id"), data.get("decision"), data.get("confidence")]).toEqual([
      ACCEPT_ID,
      "accepted",
      "high",
    ]);
    expect(reject).not.toHaveBeenCalled();
  });

  it("reject submits the reject id, the decision and the chosen reason", async () => {
    renderForms();
    fireEvent.change(screen.getByLabelText(/reject because/i), { target: { value: "duplicate" } });
    fireEvent.click(screen.getByRole("button", { name: "Reject" }));
    await waitFor(() => expect(reject).toHaveBeenCalledTimes(1));
    const data = reject.mock.calls[0][1] as FormData;
    expect([data.get("review_id"), data.get("decision"), data.get("reason_code")]).toEqual([
      REJECT_ID,
      "rejected",
      "duplicate",
    ]);
  });

  it("a retry re-sends the SAME review id (the server turns it into one review)", async () => {
    accept.mockResolvedValue({ ok: false, error: "Could not save the review. Try again." });
    renderForms();
    fireEvent.click(screen.getByRole("button", { name: "Accept" }));
    await waitFor(() => expect(accept).toHaveBeenCalledTimes(1));
    await screen.findByRole("alert");
    fireEvent.click(screen.getByRole("button", { name: "Accept" }));
    await waitFor(() => expect(accept).toHaveBeenCalledTimes(2));
    const sent = accept.mock.calls.map((c) => (c[1] as FormData).get("review_id"));
    expect(sent).toEqual([ACCEPT_ID, ACCEPT_ID]);
  });

  it("shows the server's short message, as text", async () => {
    accept.mockResolvedValue({ ok: false, error: "<b>Only an owner or admin</b>" });
    renderForms();
    fireEvent.click(screen.getByRole("button", { name: "Accept" }));
    const alert = await screen.findByRole("alert");
    expect(within(alert).queryByText("Only an owner or admin")).toBeNull();
    expect(alert.textContent).toBe("<b>Only an owner or admin</b>");
  });
});
