import {
  CONFIDENCE_LABELS,
  type ClaimSuggestionOut,
  type SuggestionTarget,
} from "@/lib/api/agents";

import { ReviewClaimForms } from "./review-claim-form";
import { reviewClaimAction } from "./suggestion-actions";

/**
 * The "Agent suggestions" section of a company / lead page.
 *
 * AN AGENT CLAIM IS A SUGGESTION until a person accepts it, and its text comes from a model that read text a stranger
 * controls: it is UNTRUSTED. Every value below is rendered as PLAIN TEXT inside ordinary elements (React escapes it); nothing
 * here builds an anchor, an image, a frame or a preview from it. Until an owner or admin accepts a suggestion it is labelled
 * "agent suggestion, unreviewed" and does not count toward any score. Sales (and Viewers) see the suggestions but get no
 * review forms; the API refuses their reviews anyway.
 */
type Props = {
  tenantId: string;
  target: SuggestionTarget;
  targetId: string;
  /** null = the API could not be reached / returned something unexpected. */
  claims: ClaimSuggestionOut[] | null;
  canReview: boolean;
  /** One pair of review ids per claim, generated by the page for this render. */
  reviewIds: Record<string, { accept: string; reject: string }>;
};

function day(iso: string): string {
  return iso.slice(0, 10);
}

export function SuggestionsPanel({ tenantId, target, targetId, claims, canReview, reviewIds }: Props) {
  const suggestions = (claims ?? []).filter((c) => c.created_via === "agent");
  return (
    <section aria-labelledby="suggestions-heading">
      <h2 id="suggestions-heading">Agent suggestions</h2>
      <p className="hint">
        Written by an agent, shown as plain text. A suggestion counts toward a score only after an owner or admin accepts it.
      </p>
      {claims === null ? (
        <p role="alert" className="error">
          Could not load the suggestions from the API. Try again shortly.
        </p>
      ) : suggestions.length === 0 ? (
        <p>No suggestions yet.</p>
      ) : (
        <ul className="evidence-list">
          {suggestions.map((claim) => (
            <li key={claim.id}>
              <p>
                <strong>{claim.value}</strong>
              </p>
              <p className="hint">
                {claim.review_state === "unreviewed" && "agent suggestion, unreviewed"}
                {claim.review_state === "accepted" &&
                  `Approved by a person${claim.review_confidence ? ` · ${CONFIDENCE_LABELS[claim.review_confidence]}` : ""}`}
                {claim.review_state === "rejected" && "Rejected by a person"}
                {" · "}
                {claim.predicate} · {day(claim.created_at)}
              </p>
              {canReview && reviewIds[claim.id] && (
                <ReviewClaimForms
                  claimId={claim.id}
                  acceptId={reviewIds[claim.id].accept}
                  rejectId={reviewIds[claim.id].reject}
                  accept={reviewClaimAction.bind(null, tenantId, target, targetId, claim.id)}
                  reject={reviewClaimAction.bind(null, tenantId, target, targetId, claim.id)}
                />
              )}
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
