"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

import {
  REVIEW_CONFIDENCES,
  REVIEW_REASONS,
  reviewClaim,
  type ReviewConfidence,
  type ReviewInput,
  type ReviewReason,
  type SuggestionTarget,
} from "@/lib/api/agents";
import { ApiAuthError, ApiRequestError } from "@/lib/api/client";
import { isCanonicalUuid } from "@/lib/api/crm";
import { requireUser } from "@/lib/auth/session";

export type ReviewActionState = { ok?: boolean; error?: string; message?: string } | undefined;

const TARGETS: readonly SuggestionTarget[] = ["companies", "leads"];

function field(formData: FormData, name: string): string {
  const value = formData.get(name);
  return typeof value === "string" ? value.trim() : "";
}

/**
 * Accept or reject ONE agent suggestion. Bound on the server to the page's tenant, target and claim.
 *
 * - The review id comes from the form, generated by the page once per render (one per button), so a double click or a retry
 *   re-sends the SAME id and the API treats it as one review.
 * - The decision, the confidence (low / medium / high: chosen by the person) and the reason are re-validated here and again
 *   by the API and the database. The browser cannot name an origin, a tenant or a confidence of the agent's own.
 * - Only an owner or admin may review; the forms are hidden for everyone else AND the API refuses them (403).
 * - The success message only says "counts toward the score" when the API reported that the workspace's profile reads this
 *   predicate (`countsTowardScore`); otherwise it says the note is not part of any score.
 * - Every failure becomes a short generic message.
 */
export async function reviewClaimAction(
  tenantId: string,
  target: SuggestionTarget,
  targetId: string,
  claimId: string,
  countsTowardScore: boolean,
  _prev: ReviewActionState,
  formData: FormData,
): Promise<ReviewActionState> {
  if (!isCanonicalUuid(targetId) || !TARGETS.includes(target))
    return { ok: false, error: "This suggestion is not available." };
  return submitReview(
    tenantId,
    claimId,
    countsTowardScore,
    formData,
    `/app/tenants/${tenantId}/${target}/${targetId}`,
  );
}

/** The same review, from the workspace's review screen (it revalidates that screen, not a company or lead page). */
export async function reviewQueueClaimAction(
  tenantId: string,
  claimId: string,
  countsTowardScore: boolean,
  _prev: ReviewActionState,
  formData: FormData,
): Promise<ReviewActionState> {
  return submitReview(
    tenantId,
    claimId,
    countsTowardScore,
    formData,
    `/app/tenants/${tenantId}/suggestions`,
  );
}

async function submitReview(
  tenantId: string,
  claimId: string,
  countsTowardScore: boolean,
  formData: FormData,
  revalidate: string,
): Promise<ReviewActionState> {
  const user = await requireUser();
  if (!isCanonicalUuid(tenantId) || !isCanonicalUuid(claimId))
    return { ok: false, error: "This suggestion is not available." };
  const id = field(formData, "review_id");
  if (!isCanonicalUuid(id))
    return { ok: false, error: "This form is out of date. Reload the page and try again." };

  const decision = field(formData, "decision");
  let input: ReviewInput;
  if (decision === "accepted") {
    const confidence = field(formData, "confidence");
    if (!(REVIEW_CONFIDENCES as readonly string[]).includes(confidence))
      return { ok: false, error: "Choose how confident you are: low, medium or high." };
    input = { id, decision, confidence: confidence as ReviewConfidence };
  } else if (decision === "rejected") {
    // a rejection needs no reason; one that is given must be one of the closed codes
    const reason = field(formData, "reason_code");
    if (reason === "") input = { id, decision };
    else if ((REVIEW_REASONS as readonly string[]).includes(reason))
      input = { id, decision, reason_code: reason as ReviewReason };
    else return { ok: false, error: "That reason is not one of the choices." };
  } else {
    return { ok: false, error: "Choose accept or reject." };
  }

  try {
    await reviewClaim(user.accessToken, tenantId, claimId, input);
  } catch (error) {
    if (error instanceof ApiAuthError) redirect("/login");
    if (error instanceof ApiRequestError) {
      if (error.status === 403)
        return { ok: false, error: "Only an owner or admin can review suggestions." };
      if (error.status === 404) return { ok: false, error: "This suggestion is not available." };
      if (error.status === 409)
        return { ok: false, error: "This form is out of date. Reload the page and try again." };
      if (error.status === 422)
        return {
          ok: false,
          error:
            "That decision is not allowed for this suggestion. Medium and high need supporting evidence: choose Low, or reject it.",
        };
    }
    return { ok: false, error: "Could not save the review. Try again." };
  }

  revalidatePath(revalidate);
  return {
    ok: true,
    message:
      decision === "accepted"
        ? countsTowardScore
          ? "Accepted. It now counts toward the score."
          : "Accepted and recorded as checked by a person. This kind of note is not part of any score yet."
        : "Rejected.",
  };
}
